server:
  port: 9005
  
spring:
  application:
    name: DEPARTMENT-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defayltZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost 