server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
     gateway:
       routes:
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
             - Path=/users/**
           filters:
             - name: CircuitBreaker
               args:
                 name: USER_SERVICE
                 fallbackuri: forward:/userServiceFallBack               
         - id: DEPARTMENT-SERVICE
           uri: lb://DEPARTMENT-SERVICE
           predicates:
             - Path=/departments/** 
           filters:
             - name: CircuitBreaker
               args:
                 name: DEPARTMENT_SERVICE
                 fallbackuri: forward:/departmentServiceFallBack   
                                 
     

hystrix:
  command:
     fallbackcmd:
       execution:
         isolation:
           thread:
             timeoutInMilliseconds: 4000
             
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream             
     
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defayltZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost      
     
     
  